CREATE TABLE images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  topic VARCHAR(50) NOT NULL UNIQUE,
  remote_path VARCHAR(255) NOT NULL,
  content_type VARCHAR(100) NOT NULL,
  alt_text VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
